[context.production]
  command = "make production"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "make deploy_preview"
  environment = { NODE_ENV = "development" }
